// End-to-end, the start page, the world map and its search, and back to Worlds: the real app on its own copy of the test world, as a user drives it.
import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { waitPhase, screenOf, lookAt, frames, sleep, stableHash } from './harness.mjs';
import { t, setup, page, noErrors, pending, openEditor, areaAction, applyArea, records } from './common.mjs';

setup({ open: false });

describe('The start page, the world map and its search, and back to Worlds', () => {

test('start page lists the test world and opens it', async () => {
  await page().goto(t.base + '/', { waitUntil: 'networkidle0' });
  await page().click('.mode[data-mode="offline"]');
  await page().waitForSelector('.world');
  const names = await page().$$eval('.world .name', e => e.map(x => x.textContent));
  assert.ok(names.includes('CITest'), `CITest listed (got ${names})`);
  await page().click('.world');
  await page().waitForFunction(() => location.pathname === '/index.html', { timeout: 60000 });
  await waitPhase(t, 'editor');
  noErrors();
});

test('world map draws', async () => {
  // Building the world map takes a while on a slow machine: wait for it rather than for the network.
  await page().goto(t.base + '/index.html', { waitUntil: 'domcontentloaded' });
  await page().waitForFunction(() => document.getElementById('loadingMap')?.hidden || document.getElementById('loadingMap')?.textContent.includes('failed'), { timeout: 180000 });
  const failed = await page().$eval('#loadingMap', e => !e.hidden && e.textContent.includes('failed'));
  assert.equal(failed, false, 'the map loads (plain colours without the game textures)');
  const w = await t.api('/api/world');
  assert.equal(w.name, 'CITest');
  assert.equal(w.saveNumber, 2);
  noErrors();
});

test('search: the map finds a kind, and its link selects the object in 3D', async () => {
  await page().goto(t.base + '/index.html', { waitUntil: 'domcontentloaded' });
  await page().waitForSelector('#sQuery');
  await page().type('#sQuery', 'beech1');
  await page().click('#sGo');
  await page().waitForSelector('#sResults .hit');
  const count = await page().$eval('#sResults .counts b', e => +e.textContent.replace(/[^0-9]/g, ''));
  const api = await t.api('/api/search?q=beech1&what=kinds');
  assert.equal(count, api.counts.Beech1, 'the count matches the world');
  await page().click('#sResults .hit');
  const href = await page().$eval('#editLink', e => e.href);
  assert.match(href, /select=-?\d+/);
  const id = +href.match(/select=(-?\d+)/)[1];
  await page().goto(href, { waitUntil: 'networkidle0' });
  await page().waitForFunction(id => window.__ed?.selection?.has(id), {}, id);
  noErrors();
});

test('zone filter: zones across the world are marked for reset and unmarked', async () => {
  await page().goto(t.base + '/index.html', { waitUntil: 'domcontentloaded' });
  await page().waitForSelector('#zShow');
  // The test world's zones were filled by the editor (not generated by the game), next to its buildings.
  for (const id of ['#zOnlyGen', '#zNoBuild', '#zNoEdit']) await page().click(id);
  await page().click('#zShow');
  await page().waitForFunction(() => /zones match/.test(document.getElementById('zInfo').textContent));
  const matching = await page().$eval('#zInfo', e => +e.textContent.match(/^([\d,]+)/)[1].replace(/,/g, ''));
  const stats = await t.api('/api/zones/stats');
  let expected = 0;
  for (let i = 0; i < stats.data.length; i += stats.stride) if (stats.data[i + 3] === 0) expected++;
  assert.ok(matching > 0, `zones match (${matching})`);
  assert.equal(matching, expected, 'every zone without buildings, and only those');
  await page().click('#zMark');
  await page().waitForFunction(() => /marked for reset/.test(document.getElementById('zInfo').textContent));
  assert.equal((await t.api('/api/world')).resetZones, matching);
  assert.match(await page().$eval('#changesText', e => e.textContent), /zone\(s\) to reset/);
  await page().click('#zUnmark');
  await page().waitForFunction(() => !/marked for reset/.test(document.getElementById('zInfo').textContent));
  assert.equal((await t.api('/api/world')).resetZones, 0);
  noErrors();
});

test('Worlds goes back to the start page', async () => {
  await page().goto(t.base + '/index.html', { waitUntil: 'networkidle0' });
  await page().click('#worldsBtn');
  await page().waitForFunction(() => location.pathname === '/' && document.querySelector('.mode'), { timeout: 60000 });
  await waitPhase(t, 'start');
  noErrors();
});

test('placed kinds have stable prefab ids', () => {
  assert.equal(stableHash('_TerrainCompiler'), -367065113);
});

});
