<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>WorldEditorBridge</AssemblyName>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>/home/thibs/Desktop/Valheim_BepInEx/BepInEx/core/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>/home/thibs/Desktop/Valheim_BepInEx/BepInEx/core/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim"><HintPath>/home/thibs/Desktop/Valheim_BepInEx/valheim_server_Data/Managed/assembly_valheim.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_utils"><HintPath>/home/thibs/Desktop/Valheim_BepInEx/valheim_server_Data/Managed/assembly_utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>/home/thibs/Desktop/Valheim_BepInEx/valheim_server_Data/Managed/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>/home/thibs/Desktop/Valheim_BepInEx/valheim_server_Data/Managed/UnityEngine.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
