import puppeteer from 'puppeteer';
const base = process.argv[2], out = process.argv[3];
const browser = await puppeteer.launch({ headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1400, height: 850 });
const errors = [];
page.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`${m.type()}: ${m.text()}`); });
page.on('pageerror', e => errors.push('pageerror: ' + e.message));
await page.goto(`${base}/editor.html?zx=0&zz=-5&size=3`, { waitUntil: 'networkidle0' });
await page.waitForFunction(() => !document.getElementById('loading'), { timeout: 60000 });
await new Promise(r => setTimeout(r, 1500));
await page.screenshot({ path: `${out}/editor-before.png` });
const before = await (await fetch(`${base}/api/world`)).json();
// Hover the centre of the view and read the status line.
await page.mouse.move(700, 470);
await new Promise(r => setTimeout(r, 300));
const statusBefore = await page.$eval('#status', e => e.innerText);
await page.click('[data-tool="raise"]');
await page.mouse.move(700, 470);
await page.mouse.down();
for (let i = 0; i < 20; i++) { await page.mouse.move(700 + i * 3, 470); await new Promise(r => setTimeout(r, 60)); }
await page.mouse.up();
await new Promise(r => setTimeout(r, 800));
const statusAfter = await page.$eval('#status', e => e.innerText);
const after = await (await fetch(`${base}/api/world`)).json();
await page.screenshot({ path: `${out}/editor-after.png` });
const undoEnabled = await page.$eval('#undo', b => !b.disabled);
await page.keyboard.down('Control'); await page.keyboard.press('z'); await page.keyboard.up('Control');
await new Promise(r => setTimeout(r, 800));
await page.mouse.move(700, 470); await new Promise(r => setTimeout(r, 300));
const statusUndo = await page.$eval('#status', e => e.innerText);
console.log(JSON.stringify({ changedBefore: before.changedZones, changedAfter: after.changedZones, undoEnabled, statusBefore, statusAfter, statusUndo, errors }, null, 1));
await page.goto(`${base}/`, { waitUntil: 'networkidle0' });
await new Promise(r => setTimeout(r, 1500));
await page.screenshot({ path: `${out}/map.png` });
await browser.close();
