import puppeteer from 'puppeteer';
const base = process.argv[2], out = process.argv[3];
const browser = await puppeteer.launch({ headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1400, height: 850 });
const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(`${base}/editor.html?zx=0&zz=-5&size=3`, { waitUntil: 'networkidle0' });
await page.waitForFunction(() => !document.getElementById('loading'), { timeout: 60000 });
await new Promise(r => setTimeout(r, 800));
await page.keyboard.press('p');
const panelVisible = await page.$eval('#pathPanel', e => !e.hidden);
await page.select('#pAction', 'flatten');
await page.evaluate(() => { const h = document.getElementById('pHeight'); h.value = 32; h.dispatchEvent(new Event('input')); });
// Click a curved line from the shore out into the water (screen points over the bay).
for (const [x, y] of [[560, 600], [600, 680], [680, 740], [790, 760]]) { await page.mouse.click(x, y); await new Promise(r => setTimeout(r, 150)); }
const info = await page.$eval('#pInfo', e => e.textContent);
await page.screenshot({ path: `${out}/path-drawn.png` });
await page.keyboard.press('Enter');
await new Promise(r => setTimeout(r, 1500));
const msg = await page.$eval('#sMsg', e => e.textContent);
await page.mouse.move(640, 715); await new Promise(r => setTimeout(r, 300));
const onLine = await page.$eval('#sHeight', e => e.textContent);
await page.screenshot({ path: `${out}/path-applied.png` });
const changed = (await (await fetch(`${base}/api/world`)).json()).changedZones;
await page.keyboard.down('Control'); await page.keyboard.press('z'); await page.keyboard.up('Control');
await new Promise(r => setTimeout(r, 800));
await page.mouse.move(641, 715); await new Promise(r => setTimeout(r, 300));
const afterUndo = await page.$eval('#sHeight', e => e.textContent);
console.log(JSON.stringify({ panelVisible, info, msg, onLine, changedZones: changed, afterUndo, errors }, null, 1));
await browser.close();
