import puppeteer from 'puppeteer';
const base = process.argv[2];
const browser = await puppeteer.launch({ headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1400, height: 850 });
const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto(`${base}/editor.html?zx=3&zz=-3&size=3`, { waitUntil: 'networkidle0' });
await page.waitForFunction(() => !document.getElementById('loading'), { timeout: 60000 });
await page.click('[data-tool="raise"]');
await page.evaluate(() => { const s = document.getElementById('strength'); s.value = 1; s.dispatchEvent(new Event('input')); });
await page.mouse.move(700, 430); await page.mouse.down();
await new Promise(r => setTimeout(r, 4000));
await page.mouse.up(); await new Promise(r => setTimeout(r, 600));
await page.mouse.move(701, 430); await new Promise(r => setTimeout(r, 300));
const h = await page.$eval('#sHeight', e => e.textContent), msg = await page.$eval('#sMsg', e => e.textContent);
console.log(JSON.stringify({ h, msg, errors }, null, 1));
await browser.close();
