import puppeteer from 'puppeteer';
const [base, out] = process.argv.slice(2);
const browser = await puppeteer.launch({ headless: true, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1400, height: 850 });
const errors = []; page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (['error', 'warning'].includes(m.type())) errors.push(m.text().slice(0, 600)); });
await page.goto(`${base}/editor.html?zx=-9&zz=-6&size=3`, { waitUntil: 'networkidle0' });
await page.waitForFunction(() => document.getElementById('lookState')?.textContent === '' && document.querySelector('[data-count="trees"]').textContent !== '', { timeout: 120000 });
await page.evaluate(() => window.__view(0, 140, 120, 0, 60, 0));
await new Promise(r => setTimeout(r, 2500));
const counts = await page.$$eval('[data-count]', els => els.map(e => e.dataset.count + e.textContent));
await page.click('input[data-show="trees"]');
await new Promise(r => setTimeout(r, 2000));
await page.screenshot({ path: `${out}/show-notrees.png` });
await page.click('#terrainOnly');
await new Promise(r => setTimeout(r, 2000));
await page.screenshot({ path: `${out}/show-terrain.png` });
await page.reload({ waitUntil: 'networkidle0' });
await page.waitForFunction(() => document.getElementById('lookState')?.textContent === '', { timeout: 120000 });
const remembered = await page.$$eval('[data-show]', els => els.filter(e => e.checked).length);
await page.click('#showAll');
console.log(JSON.stringify({ counts, remembered, errors }));
await browser.close();
