using TerrainEditor.Editing;
using TerrainEditor.Save;

namespace TerrainEditor.App;

// Every zone of the save (generated by the game, or holding objects or ground edits), with what the
// map's zone filter (like MCA Selector) needs to pick zones to reset across the whole world: biome,
// player-built pieces, ground edits, how many objects, and how far (in zones) the nearest zone with
// buildings is.
public static class ZoneStats
{
	// Per zone: x, z, biome (Heightmap.Biome value), pieces, ground edited (0/1), objects, distance in zones
	// to the nearest zone with pieces (-1 when the world has none), generated by the game (0/1).
	public const int Stride = 8;

	public static int[] Compute(WorldSave world, EditStore edits, Func<int, int, int> biomeOf)
	{
		if (world.Zones == null)
		{
			return Array.Empty<int>();
		}
		int maxZone = (int)Math.Ceiling(ValheimGen.TerrainService.MapRadius / 64f) + 1;
		HashSet<int> deleted = edits.Deleted;
		Dictionary<(int, int), int> pieces = new(), objects = new();
		for (int id = 0; id < world.ObjectRefs.Count; id++)
		{
			ObjectRef o = world.ObjectRefs[id];
			if (deleted.Contains(id) || o.IsTerrain)
			{
				continue;
			}
			var key = o.Zone;
			objects[key] = objects.GetValueOrDefault(key) + 1;
			if (o.IsPiece)
			{
				pieces[key] = pieces.GetValueOrDefault(key) + 1;
			}
		}
		HashSet<(int, int)> edited = edits.All().Where(e => e.HeightCount + e.PaintCount > 0).Select(e => (e.ZoneX, e.ZoneZ)).ToHashSet();
		// Distance to buildings: a breadth-first walk out from every zone with pieces (8 neighbours, so
		// the distance is the larger of the x and z steps).
		int size = maxZone * 2 + 1;
		int[] dist = new int[size * size];
		Array.Fill(dist, -1);
		Queue<(int, int)> queue = new();
		foreach (var (x, z) in pieces.Keys)
		{
			if (Math.Abs(x) <= maxZone && Math.Abs(z) <= maxZone)
			{
				dist[(z + maxZone) * size + x + maxZone] = 0;
				queue.Enqueue((x, z));
			}
		}
		while (queue.Count > 0)
		{
			var (x, z) = queue.Dequeue();
			int d = dist[(z + maxZone) * size + x + maxZone];
			for (int dz = -1; dz <= 1; dz++)
			{
				for (int dx = -1; dx <= 1; dx++)
				{
					int nx = x + dx, nz = z + dz;
					if (Math.Abs(nx) > maxZone || Math.Abs(nz) > maxZone)
					{
						continue;
					}
					int i = (nz + maxZone) * size + nx + maxZone;
					if (dist[i] < 0)
					{
						dist[i] = d + 1;
						queue.Enqueue((nx, nz));
					}
				}
			}
		}
		HashSet<(int, int)> generated = world.Zones.Generated.Select(g => ((int)g.X, (int)g.Z)).ToHashSet();
		List<(int X, int Z)> zones = generated.Union(objects.Keys).Union(edited)
			// Only zones in the world: an empty server also generates zones around a far-away point.
			.Where(g => Math.Abs(g.Item1) <= maxZone && Math.Abs(g.Item2) <= maxZone && MathF.Sqrt(g.Item1 * g.Item1 + g.Item2 * g.Item2) * 64f <= ValheimGen.TerrainService.MapRadius + 64f)
			.OrderBy(g => g.Item2).ThenBy(g => g.Item1).ToList();
		int[] biomes = new int[zones.Count];
		Parallel.For(0, zones.Count, i => biomes[i] = biomeOf(zones[i].X, zones[i].Z));
		int[] result = new int[zones.Count * Stride];
		for (int i = 0; i < zones.Count; i++)
		{
			var (x, z) = zones[i];
			int o = i * Stride;
			result[o] = x;
			result[o + 1] = z;
			result[o + 2] = biomes[i];
			result[o + 3] = pieces.GetValueOrDefault((x, z));
			result[o + 4] = edited.Contains((x, z)) ? 1 : 0;
			result[o + 5] = objects.GetValueOrDefault((x, z));
			result[o + 6] = dist[(z + maxZone) * size + x + maxZone];
			result[o + 7] = generated.Contains((x, z)) ? 1 : 0;
		}
		return result;
	}
}
