using Avalonia.Controls;
using TerrainEditor.App;

namespace TerrainEditor.Desktop;

// Hover help for every control, in one place (the web editor's tips.js): the same wording as the
// documentation (docs/), so the two stay in step. A control takes its text with .Tip("key"); a row's
// label shows its control's tip too (Tips.Label).
public static class Tips
{
	public static readonly IReadOnlyDictionary<string, string> Texts = new Dictionary<string, string>
	{
		// ---- Top bar of the editor
		["top.map"] = "Back to the world map. What is not saved or applied stays pending.",
		["top.save"] = "Write the changes into the world files (Ctrl+S). Like Apply live, the history stays: undo a step and save again to take it back.",
		["top.apply"] = "Send the pending changes to the running game (Ctrl+S): everyone there sees them at once.",
		["top.discard"] = "Undo every change that is not saved or applied yet. Saved and applied changes stay.",
		["top.reload"] = "Load the world again from the running game (picks up what players changed since).",
		["top.auto"] = "Live: send every stroke, placement and undo to the game right away, without pressing Apply live.",
		["top.history"] = "Every change of this session: roll back to any point, or remove one change (L).",
		["top.view"] = "Show or hide kinds of things in the world, and the look options (V).",
		["top.help"] = "Mouse controls and keyboard shortcuts (?).",
		["top.areaSize"] = "The area's size: 3 × 3, 5 × 5 or 7 × 7 zones around the same middle zone, changed on the fly. What you changed and the history stay.",
		["top.follow"] = "Follow the view: when the point you look at comes near the edge of the area, the area moves there by itself (it waits while a path, shape, selection or stroke is unfinished).",
		["top.west"] = "Move the area one zone (64 m) west. Pending changes stay.",
		["top.north"] = "Move the area one zone (64 m) north. Pending changes stay.",
		["top.south"] = "Move the area one zone (64 m) south. Pending changes stay.",
		["top.east"] = "Move the area one zone (64 m) east. Pending changes stay.",
		["card.close"] = "Close this panel.",
		["note.close"] = "Hide this note.",

		// ---- Brush settings (sculpt and paint tools)
		["brush.size"] = "Brush radius in metres. [ and ] change it.",
		["brush.strength"] = "How fast the brush works while you hold the mouse button.",
		["brush.shape"] = "Shape of the brush: circle, square, ring (only a band around the middle: rims and moats), ragged (a noisy edge for natural-looking strokes), or a picture (stamps).",
		["brush.falloff"] = "How the effect fades from the middle to the edge: smooth, linear, dome (round top), flat top (full strength almost to the edge), peak (strong in the middle only), or sharp edge (full strength right to the edge: steep walls, like the pickaxe).",
		["brush.turn"] = "Turn of a square brush or a picture (degrees). , and . change it (Shift: 15°).",
		["brush.loadStamp"] = "Load a picture (PNG, JPEG...) as a brush shape: white parts work fully, black parts not at all. It is kept for next time.",
		["brush.forgetStamp"] = "Forget the loaded picture chosen as Shape (built-in stamps stay).",
		// ---- Script tool
		["script.pick"] = "An example to start from, or a script you saved (Save keeps them in the data folder's scripts folder).",
		["script.code"] = "The script: C# statements run on the open area, with Area, Ground, Objects, Noise, Rnd and Print. Ctrl+Enter runs it.",
		["script.name"] = "The name to save the script under.",
		["script.save"] = "Save the script (as <name>.csx in the data folder's scripts folder), to pick it again later.",
		["script.run"] = "Compile and run the script on the open area (Ctrl+Enter): everything it changes is one undo step.",
		["script.stop"] = "Stop the running script: nothing it did is kept. (A loop that never calls the editor cannot be stopped; it ends after 2 minutes.)",
		// ---- Mountain tool
		["mountain.preset"] = "What kind of mountain: a lone peak, a ridge, a mountain range, a mesa (flat top), a volcano or rolling hills. Choosing one rolls a new one (Randomize).",
		["mountain.height"] = "How high it rises above the ground there (m). Past the game's ±8 m: saving turns it into ground discs.",
		["mountain.radius"] = "How far it reaches from where you click (m); its outline is ragged, up to 15% further. The circle shows it.",
		["mountain.rough"] = "How rugged its slopes are: 0 smooth, 1 deep gullies and ridges.",
		["mountain.turn"] = "The direction a ridge or range runs (degrees).",
		["mountain.seed"] = "The number its detail is made from: the same seed and values make the same mountain again.",
		["mountain.randomize"] = "A new mountain of the preset: new size, roughness, direction and seed.",
		["mountain.clear"] = "Take away the trees, rocks, ore, bushes and pickables it would bury (saving does it anyway where the ground rises more than 2 m). Buildings stay.",
		["mountain.grow"] = "Then grow the biome's own trees and rocks on its slopes, by the game's rules (another undo step).",
		// ---- Cave (Path tool)
		["cave.preset"] = "A tunnel, cave or cavern: width, wall slope, depth and headroom to start from.",
		["cave.randomize"] = "New sizes around the preset's, and new boulders for the roof.",
		["cave.depth"] = "How far below the ground the cave's floor is in the middle (m); the ends slope up to the ground as entrances. Past 8 m needs No limit (brush options).",
		["cave.headroom"] = "The height inside, floor to the boulders' undersides (m). The roof goes only where the cave is deeper than this by 1.5 m.",
		["cave.rock"] = "The boulders the roof is made of: the game's big world rocks (players can mine them, like any boulder). By biome: heath rocks in the Plains, mountain rocks in the Mountains, coast rocks by the sea, forest rocks elsewhere.",
		["brush.noLimit"] = "On: Raise, Lower, Flatten, the Path and Area tools and pasting move the ground as far as you like, not just the game's ±8 m. "
			+ "Saving (or Apply live) turns that ground into invisible ground discs every player's game counts as generated ground, console players too: no mod needed. "
			+ "The hoe and pickaxe then get their ±8 m from the new ground. Trees, rocks and bushes where the ground moved more than 2 m are taken away. "
			+ "Very steep walls come out a little softer.",
		["brush.stampOnce"] = "With a stamp as Shape, a click of Raise or Lower puts the whole stamp into the ground at once, to the Height below, instead of painting.",
		["brush.stampHeight"] = "How high (Raise) or deep (Lower) the white parts of the stamp go (m).",
		["brush.targetFromClick"] = "On: Flatten levels to the height of the ground where you start the stroke. Off: it levels to the Height below.",
		["brush.target"] = "The height (m) Flatten levels to when the option above is off. Alt + click the ground to pick its height.",
		["natural.amp"] = "How tall the natural bumps are (m).",
		["natural.size"] = "How wide the natural bumps are (m): small values give rough ground, large values gentle swells.",
		["natural.seed"] = "Pick a new random bump pattern for the next Naturalize stroke or natural path.",
		["erode.thermal"] = "Thermal: where the ground is steeper than the rest angle, it slides down to its neighbours (screes, softened cliffs).",
		["erode.water"] = "Water: rain drops run downhill, dig where they speed up and leave what they carry where they slow down (gullies, fans, smooth valleys).",
		["erode.rest"] = "Thermal: the steepest slope that stays put (degrees). Lower values flatten more.",

		// ---- Shape tool
		["shape.preset"] = "The shape to put in. Each one is a formula (shown below) that you can change; Formula… keeps your own.",
		["shape.radius"] = "Radius of the shape (m). Only the ground within it changes.",
		["shape.height"] = "Height of the shape (m), as h in the formula. Craters, moats and bowls dig this deep.",
		["shape.formula"] = "Metres to add to the ground at each point. x, z: metres east and north of the click; d: distance from it; r: radius; h: height; n(x, z): noise from -1 to 1.",

		// ---- Path tool
		["path.action"] = "What happens along the line when you press Apply.",
		["path.width"] = "Width of the path (m).",
		["path.soft"] = "Width of the soft edge on each side (m), blending the path into the ground around it.",
		["path.height"] = "Flatten to height: the height of the path (m). Alt + click the ground to pick it.",
		["path.amount"] = "Raise / Lower by: how much to raise or lower along the path (m).",
		["path.start"] = "Ramp: height at the first point (m). Alt + click the ground to pick it.",
		["path.end"] = "Ramp: height at the last point (m). Alt + Shift + click the ground to pick it.",
		["path.depth"] = "River / canal: depth of the bed below sea level in the middle (m). The bed rises to the waterline at the path's width; the soft edge makes the banks. It only digs.",
		["path.curve"] = "On: a smooth curve through your points. Off: straight lines between them.",
		["path.natural"] = "Ragged edges, varying width and small bumps, so the path looks worn rather than tool-made.",
		["path.apply"] = "Do the chosen action along the line (Enter). The line stays, so you can apply another action to it.",
		["path.clear"] = "Remove the line (Esc).",

		// ---- Mask
		["mask.on"] = "Limit brushes, paths, area actions and placing to ground that matches all the settings below.",
		["mask.biome"] = "Only ground of the biomes switched on here (none on: every biome).",
		["mask.hmin"] = "Only ground at or above this height (m). Empty = no limit. Alt + Shift + click fills the range around a spot.",
		["mask.hmax"] = "Only ground at or below this height (m). Empty = no limit.",
		["mask.smin"] = "Only ground at least this steep (degrees). Empty = no limit.",
		["mask.smax"] = "Only ground at most this steep (degrees). Empty = no limit; 0 lets only perfectly flat ground through.",
		["mask.paint"] = "Only ground with this paint.",

		// ---- Measure
		["measure.clear"] = "Remove the measurement (Esc).",

		// ---- Select
		["select.delete"] = "Remove the selected objects from the world (Del). Ctrl+Z brings them back.",
		["select.building"] = "Add every building piece connected to the selected ones, through pieces that touch (double-clicking a piece does it too).",
		["select.same"] = "Select every shown object in the area of the kinds that are selected now (all the beeches, all the chests...).",
		["select.invert"] = "Select every shown object in the area that is not selected now, and only those.",
		["select.ground"] = "On: trees, rocks and other objects each land on the ground; building pieces move as one block that keeps its shape, with its bottom layer on the ground. Off: each object keeps its height above the ground.",
		["select.snap"] = "While moving, a piece's snap point locks onto the nearest snap point of a piece around it (within 0.75 m), so walls, floors and fences join like with the hammer.",
		["select.x"] = "World position east-west (m) of the selection's middle (or of the one object).",
		["select.y"] = "Height (m) of the lowest selected object.",
		["select.z"] = "World position north-south (m).",
		["select.turn"] = "Turn (degrees, clockwise seen from above) of the first selected object; the others turn with it around the middle.",
		["select.apply"] = "Move and turn the selection to the typed values (one undo step). No snapping on top of typed values.",
		["select.by"] = "Type amounts to move and turn by, instead of where to go.",
		["select.to"] = "The kind to put in place of each selected object.",
		["select.replace"] = "Replace every selected object by the chosen kind, at the same place and facing.",
		["select.pick"] = "Pick the kind from the world: click an object to put its kind in the list (Esc cancels).",
		["select.saved"] = "Selections kept for this world. They are found again by kind and position, also after the world is saved.",
		["select.keep"] = "Keep the selection under a name, to pick it again later.",
		["select.load"] = "Select the objects of this saved selection (instead of the current selection).",
		["select.add"] = "Add the objects of this saved selection to the current selection.",
		["select.forget"] = "Forget this saved selection.",
		["select.claim"] = "Give the selected pieces that have no builder the one chosen in View, Built by, so the game treats them as player built. One undo step.",
		["select.inspect"] = "Show everything the selected object holds in the save (sign text, portal tag, chest contents, timers...) and change it (I).",

		// ---- Inspector
		["inspect.apply"] = "Replace the object by a copy with the changed data (one undo step). Save or Apply live writes it.",
		["inspect.revert"] = "Forget the changes made here.",
		["inspect.addSection"] = "What kind of value to add.",
		["inspect.addKey"] = "The name of the value, as the game calls it (text for a sign, tag for a portal...), or its number.",
		["inspect.addValue"] = "The value to add.",
		["inspect.add"] = "Add this value to the object (applied with Apply changes).",
		["inspect.value"] = "The value as it is saved; change it, then Apply changes.",
		["inspect.item"] = "The item's name as the game knows it (the list completes it).",
		["inspect.count"] = "How many of the item are in the stack.",
		["inspect.quality"] = "The item's quality (upgrade level).",
		["inspect.durability"] = "The item's durability.",
		["inspect.slotX"] = "The item's column in the container.",
		["inspect.slotY"] = "The item's row in the container.",
		["inspect.removeValue"] = "Remove this value from the object (applied with Apply changes).",
		["inspect.keepValue"] = "Keep this value after all.",
		["inspect.unadd"] = "Do not add this value after all.",
		["inspect.removeItem"] = "Take this item out of the container.",
		["inspect.addItem"] = "Add an item (Wood) in the first free slot; change its name and stack.",
		["inspect.tidy"] = "Put every item in the first free slots, row by row.",

		// ---- Area
		["area.box"] = "Drag a rectangle on the ground.",
		["area.poly"] = "Click corners; double-click or Enter closes the shape. Backspace removes the last corner.",
		["area.clear"] = "Clear the selection, to start a new one (Esc).",
		["area.soft"] = "Ground actions fade out over this many metres inside the edge of the selection.",
		["area.action"] = "What to do with the selection: only its own settings are shown, then Apply (Enter) does it.",
		["area.height"] = "Height (m) used by Flatten.",
		["area.avg"] = "Set Height to the average ground height inside the selection.",
		["area.amount"] = "Metres used by Raise and Lower.",
		["area.paint"] = "Paint to put on the ground inside.",
		["area.kind"] = "Which kinds of objects Remove, Select, Replace, Regrow and Restore from a backup act on: switch a kind on or off.",
		["area.from"] = "The kind of object to replace.",
		["area.to"] = "The kind to put in its place.",
		["area.pick"] = "Pick the kind from the world: click an object to put its kind in the list (Esc cancels).",
		["area.copy"] = "Copy the ground shape, paint and shown objects inside the selection (Ctrl+C).",
		["area.paste"] = "Paste the copy (Ctrl+V): click to place it, here or in another area.",
		["area.saveBlueprint"] = "Save the clipboard as a blueprint: a file with a name, kept in the editor's data folder, that can be pasted into any world.",
		["area.library"] = "Open the list of saved blueprints, with a picture of each: paste one, or delete it.",
		["area.export"] = "Write the ground of the whole area as a 16-bit grayscale PNG (black lowest, white highest, north at the top, 1 pixel per metre). The heights are kept in the picture.",
		["area.import"] = "Read a grayscale picture and fit it to the selection (or the whole area, without a selection).",
		["area.lowest"] = "Height (m) for black in the picture.",
		["area.highest"] = "Height (m) for white in the picture.",
		["area.put"] = "Set the ground to the picture's heights (one undo step). The soft edge, the Mask and the ±8 m limit apply.",
		["area.cancelPicture"] = "Forget the picture without changing the ground.",
		["area.backup"] = "The backup to restore from: the game's own backups (and older editor ones), newest first, or another copy of this world.",
		["area.backupGround"] = "Put the ground (height and paint) inside the selection back as it was in the backup.",
		["area.backupObjects"] = "Put the objects of the kinds chosen above back as they were in the backup, with all their data. Unchanged objects stay as they are.",
		["area.keepBuildings"] = "Player-built pieces in the zones are kept when they are reset.",
		["area.resetGround"] = "Also undo the ground edits in the zones (height and paint).",
		["area.unreset"] = "Cancel the reset of the zones under the selection.",
		["areaAct.Flatten"] = "Level the ground inside to the Height below.",
		["areaAct.Raise"] = "Lift the ground inside by the Amount below.",
		["areaAct.Lower"] = "Dig the ground inside down by the Amount below.",
		["areaAct.Smooth"] = "Even out bumps inside the selection.",
		["areaAct.Natural"] = "Natural-looking bumps inside the selection (Bumps and Bump size of the Naturalize tool).",
		["areaAct.Restore"] = "Put the ground inside back to how the world generated it, and remove paint.",
		["areaAct.Erode"] = "Weather the ground inside the selection: slopes settle and rain cuts gullies (rest angle from the Erode tool).",
		["areaAct.Paint"] = "Paint the ground inside the selection.",
		["areaAct.Remove"] = "Remove the objects of the kinds switched on inside the selection.",
		["areaAct.Select"] = "Select the objects of the kinds switched on inside the selection (then use the Select tool on them).",
		["areaAct.Replace"] = "Replace every object of the first kind inside the selection by the second kind.",
		["areaAct.Regrow"] = "Put back what the game grows here: its own trees, rocks, bushes and pickables for the biome, by its vegetation rules, for the kinds switched on. Skips spots where something stands and the ground near buildings.",
		["areaAct.Copy"] = "Copy the selection, paste it, or keep it as a blueprint.",
		["areaAct.Heightmap"] = "Write the area's ground as a grayscale picture, or put a picture into the ground.",
		["areaAct.Backup"] = "Restore the selection from the chosen backup (one undo step). Save or Apply live writes it.",
		["areaAct.Reset"] = "On save, the zones under the selection lose their trees, rocks, ruins and dungeon entrances; the game generates them again when someone goes there.",

		// ---- Paste
		["paste.ground"] = "Paste the copied ground shape and paint.",
		["paste.objects"] = "Paste the copied objects.",
		["paste.offset"] = "Move the pasted ground and objects up or down (m); Ctrl + wheel too (Shift: 0.1 m). Lower a building into a hill: Clear the site digs the ground in its way.",
		["paste.turn"] = "Turn the paste a quarter turn (R). , and . or Alt + wheel turn it by 1° (Shift: 15°).",
		["paste.mirror"] = "Mirror the paste (F).",
		["paste.done"] = "Stop pasting (Esc).",
		["paste.copies"] = "How many copies one click places, side by side (like WorldEdit's //stack). 1 = a single paste.",
		["paste.along"] = "Which way the copies follow each other: along the copy's width or depth (turning with it), or stacked upwards.",
		["paste.gap"] = "Space left between two copies (m); negative values make them overlap.",

		// ---- Place
		["place.brush"] = "Paint objects under the brush: a click places what the preview shows, a drag keeps adding.",
		["place.line"] = "Place objects at a fixed spacing along a line you draw.",
		["place.grid"] = "Drag a box: one object in the middle of each cell.",
		["place.zone"] = "Draw a zone freely, then fill it by scatter or by a grid.",
		["place.preset"] = "Load a mix: its kinds with their weights, and its Density, Spacing, Size, Tilt and facing. Built-in looks, and the ones you saved.",
		["place.savePreset"] = "Save the chosen kinds, their weights and the Density, Spacing, Size, Tilt and facing settings under a name.",
		["place.deletePreset"] = "Delete the chosen preset (only your own).",
		["place.kinds"] = "Open or close the list of kinds to choose from: search, favourites, recent kinds, or pick one in the world.",
		["place.search"] = "Filter the list of kinds by name.",
		["place.kind"] = "Tick to place this kind (with the others ticked); ☆ keeps it among the favourites.",
		["place.pick"] = "Pick a kind from the world: click an object to place only that kind. Shift + click adds it to the ticked kinds. Esc cancels.",
		["place.favourite"] = "A starred kind. Click: tick or untick it (Shift + click: place only this kind).",
		["place.recent"] = "A kind you placed lately. Click: tick or untick it (Shift + click: place only this kind).",
		["place.untickAll"] = "Untick every kind.",
		["place.favAll"] = "Tick every favourite.",
		["place.favNone"] = "Untick every favourite.",
		["place.recentAll"] = "Tick every recent kind.",
		["place.recentNone"] = "Untick every recent kind.",
		["place.group"] = "Open or fold this category: ticked / all kinds in it. Searching opens every category with a match.",
		["place.size"] = "Brush radius in metres. [ and ] change it.",
		["place.density"] = "Brush and zone scatter: objects per 100 m².",
		["place.spacing"] = "Brush and Zone: minimum distance between objects (m), also from objects already there.",
		["place.clump"] = "Brush and Zone: gather the objects in groves with clearings between them, like natural forests. 0: an even spread; higher: smaller, fewer groves. New layout (R) moves them.",
		["place.patch"] = "Clumping: the size of the groves and clearings (m).",
		["place.sizeMin"] = "Smallest size, in % of the normal size. Each object gets a random size between the two values.",
		["place.sizeMax"] = "Largest size, in % of the normal size.",
		["place.tilt"] = "Random lean of each object, up to this many degrees.",
		["place.rotation"] = "Turn of the preview layout and of each object's facing (degrees). , and . or Alt + wheel change it.",
		["place.randomYaw"] = "On: each object faces a random direction. Off: they all face the Rotation.",
		["place.elevation"] = "Where placed objects stand: on the ground, a height above the ground, or all at one height. PgUp / PgDn change it, Alt + click picks it.",
		["place.elev"] = "Metres above the ground, or the height in metres (its bottom there) for At one height.",
		["place.snapTo"] = "Building pieces lock onto the snap points of the pieces already there, like the hammer: beside them or on top.",
		["place.beside"] = "Snap end to end with the piece next to the cursor, at its level.",
		["place.onTop"] = "Snap on top of the piece under the cursor.",
		["place.layers"] = "Stack the line this many pieces high, each layer on top of the one below.",
		["place.single"] = "Place one object exactly under the cursor per click (only an object right on the spot blocks it).",
		["place.grow"] = "Keep saplings and crops at least their in-game grow radius away from everything, so they can grow; grown crops and trees keep the room their sapling needs.",
		["place.endToEnd"] = "Line: each object starts exactly where the last one ends, turned along the line, like the game's hammer snaps pieces (fences, walls, stakes, floors...). Switches itself on when every ticked kind is a piece the game snaps.",
		["place.loop"] = "Line: go back to the first point at the end, to fence a zone in.",
		["place.every"] = "Line: distance between two objects along the line (m).",
		["place.wiggle"] = "Line: random sideways offset from the line, up to this many metres.",
		["place.along"] = "Line: each object follows the line (plus the Rotation): pieces lie along it, others face along it. Off: random facing. Circles and rectangles always follow their outline.",
		["place.curve"] = "Line: a smooth curve through your points instead of straight segments.",
		["place.cell"] = "Grid: space between objects, centre to centre (m). Each object sits in the middle of a cell this size.",
		["place.place"] = "Place the objects the preview shows (Enter).",
		["place.clearShape"] = "Remove the drawn line, box or zone (Esc).",
		["place.undoPoint"] = "Remove the last point you clicked (Backspace). Ctrl + click any point to remove that one.",
		["place.newLayout"] = "New random choices for the preview: positions, kinds, sizes and facings (R).",
		["place.weight"] = "How often this kind is used compared to the other ticked kinds (Beech 3, Birch 1: three beeches for one birch).",
		["place.unchoose"] = "Stop placing this kind.",
		["place.fit"] = "Set the spacing to the widest ticked kind, so they stand side by side without overlapping.",

		// ---- View panel
		["view.gameLook"] = "Draw the world with the game's own textures, models, water and sky. Off: flat colours and boxes, faster.",
		["view.seeThrough"] = "Make buildings half see-through, to see the ground and objects inside them.",
		["view.res3d"] = "How many pixels the 3D view draws. Sharp: the screen's own. Balanced: one per screen point. Fast: fewer still. Fewer pixels give more frames per second.",
		["view.water"] = "The sea surface.",
		["view.unsaved"] = "A green dot over each new object not saved (or applied) yet. Off: no dots (the objects stay).",
		["view.limit"] = "Red on the ground that reached the game's limit of ±8 m from its original height (in Game look). Off: no red (the ground stays as edited).",
		["view.slope"] = "Colour the ground by steepness (needs Game look).",
		["view.contour"] = "Draw height lines every chosen number of metres.",
		["view.contourStep"] = "Distance between height lines (m).",
		["view.builder"] = "The player written as the builder of every piece you place (hammer, hoe, cultivator and serving tray kinds), so the game treats them as player built: full materials back, a base for fires, raids, and wards and private chests that answer to that player. The list has the world's builders and this computer's characters; Nobody places pieces without a builder (as parts of a ruin).",
		["view.defaults"] = "Back to the default switches (spoilers off).",
		["view.all"] = "Show everything.",
		["view.ground"] = "Show only the ground: every kind of object, the water and the overlays off.",
		["view.perf"] = "Write the frame rate to a log file, a line every 0.2 s while the view is used. Off each time the editor opens.",
		["view.player"] = "Live: the player to go to.",
		["view.goPlayer"] = "Go to the player: right there when they are in the area, else the area moves to them.",
		["overlay.borders"] = "Lines between the 64 m zones.",
		["overlay.markers"] = "Markers where the game placed locations (villages, dungeons, the trader...) (spoiler).",
		["overlay.wards"] = "Rings on the ground where each ward protects (no building or opening chests there without its permission).",
		["overlay.stations"] = "Rings on the ground where each workbench, forge or other crafting station lets you build and upgrade.",
		["overlay.flatten"] = "Where locations flatten the ground: a ring for the flat part, a fainter one where it blends into the land.",

		// ---- Map page
		["map.worlds"] = "Back to the start page to open another world.",
		["map.save"] = "Write every pending change into the world files.",
		["map.apply"] = "Send every pending change to the running game (everyone sees it at once).",
		["map.discard"] = "Forget every change that is not saved or applied yet: the world is read again.",
		["map.reload"] = "Load the world again from the running game.",
		["map.buildings"] = "Draw the footprint of every player-built piece on the map.",
		["map.grid"] = "Lines between the 64 m zones.",
		["map.edited"] = "Outline the zones with changes waiting to be saved or applied, and the zones marked for reset.",
		["map.paint"] = "When zoomed in close, show the painted ground (dirt, paved, cultivated) as the game does.",
		["map.clouds"] = "Draw the game's clouds over the map, as on the in-game map.",
		["map.edit"] = "Open the 3D editor on the zones around the picked spot.",
		["map.size"] = "How much ground the 3D editor loads around the spot (bigger is slower).",
		["map.search"] = "Part of a name or text; not case sensitive.",
		["map.searchWhat"] = "What to look for: objects by their kind, items in chests and other containers, or texts (signs, portals, wards...).",
		["map.find"] = "Search every object of the world (Enter).",
		["map.biome"] = "Only zones of the biomes switched on here (none on: every biome).",
		["map.noBuild"] = "Leave out zones with player-built pieces, and zones close to them.",
		["map.dist"] = "How many zones around a building also count as close to it.",
		["map.noEdit"] = "Leave out zones whose ground was edited (in game or in the editor).",
		["map.onlyGen"] = "Only zones the game has generated already (visited by a player).",
		["map.rmin"] = "Only zones at least this far from the centre of the world (m). Empty: no limit.",
		["map.rmax"] = "Only zones at most this far from the centre of the world (m). Empty: the world's edge.",
		["map.ground"] = "Also undo the ground edits of the zones (only matters when No ground edits is off).",
		["map.show"] = "Show the matching zones on the map (blue).",
		["map.mark"] = "Mark the matching zones for reset (red); Save or Apply live does it.",
		["map.unmark"] = "Cancel every zone reset that is marked.",

		// ---- Start page
		["start.settings"] = "Where the game, BepInEx and worlds are on this computer.",
		["start.docs"] = "The editor's documentation, in your web browser.",
		["start.game"] = "Edit the world you are playing in, single player or the one you host. You see the changes in game right away.",
		["start.server"] = "Edit your server's world while people play. The editor connects to the server itself.",
		["start.offline"] = "Edit world files on this computer with the game closed, then start the game again.",
		["start.editLive"] = "Open the world the game is playing in, live.",
		["start.folder"] = "A world folder: the one with the _main.<n>.chunks files.",
		["start.browse"] = "Choose the folder.",
		["start.open"] = "Open this world folder.",
		["start.world"] = "Open this world (offline: close the game first).",
		["start.host"] = "The server's address (name or IP), or user@address.",
		["start.sshPort"] = "The server's SSH port (22 unless it was changed).",
		["start.user"] = "The account you log in to the server with.",
		["start.password"] = "The account's password. Leave it empty to log in with a key file.",
		["start.savePassword"] = "Keep the password with the saved server, so you do not type it again.",
		["start.keyFile"] = "Your private SSH key file, when the server takes keys (empty: the usual keys in ~/.ssh).",
		["start.passphrase"] = "The key file's passphrase, when it has one.",
		["start.token"] = "The plugin's token: the Token line of BepInEx/config/Tie.WorldEditorBridge.cfg on the server.",
		["start.bridgePort"] = "The plugin's port on the server (5182 unless it was changed in its settings).",
		["start.gameFolder"] = "The server's Valheim folder (with BepInEx): the editor reads the plugin's port there and says precisely why it does not answer.",
		["start.name"] = "How the server shows in your list.",
		["start.connect"] = "Log in to the server, make the tunnel and open its world.",
		["start.bridgeUrl"] = "The plugin's address, when you made the tunnel yourself (or the game runs on this computer).",
		["start.connectUrl"] = "Open the world of the game at this address.",
		["start.savedConnect"] = "Connect to this server.",
		["start.savedEdit"] = "Change this server's settings.",
		["start.savedForget"] = "Remove this server from the list (its password and token are forgotten too).",
		["start.savedToken"] = "The plugin's token for this server.",
		["start.savedPassword"] = "The password for this server.",
		["look.path"] = "The folder Steam installed Valheim into (the one with valheim_Data).",
		["look.browse"] = "Choose the Valheim folder.",
		["look.use"] = "Copy the game's look from this folder.",
		["look.retry"] = "Try to copy the game's look again.",

		// ---- Settings
		["settings.valheim"] = "The Valheim game folder (with valheim_Data). Empty: found in the Steam libraries.",
		["settings.browse"] = "Choose the folder.",
		["settings.auto"] = "Find Valheim in the Steam libraries by itself.",
		["settings.folder"] = "A folder to look in.",
		["settings.remove"] = "Remove this folder from the list.",
		["settings.add"] = "Add a folder to the list.",
		["settings.save"] = "Keep these folders.",

		// ---- Blueprints and History
		["blueprints.search"] = "Filter the blueprints by name.",
		["blueprints.new"] = "Open the Workshop, a blank plot, to build a building and save it as a blueprint.",
		["workshop.support"] = "On: every building piece is outlined in the colour the game gives its support in build mode (blue on the ground, then green to red), and pieces that would fall in game are pink. Off: build freely.",
		["top.saveBlueprint"] = "Save the building pieces on the plot as a Homestead blueprint (nothing else is kept).",
		["start.workshop"] = "Build on a blank plot, then keep it as a blueprint for Homestead. Your blueprints are in its Library.",
		["build.piecesTab"] = "The pieces to build with, in the game's tabs.",
		["build.libraryTab"] = "Your blueprints (Homestead's): open one, add one to the plot, or drag it onto the plot.",
		["build.librarySearch"] = "Find blueprints by name, description or tags.",
		["build.open"] = "This blueprint alone on the plot (asks first when what is there is not saved).",
		["build.add"] = "Add this blueprint to the plot, in its middle, with what is there (one undo step).",
		["blueprints.getHomestead"] = "Opens Homestead's page on Thunderstore: install it in your Valheim (a mod manager does it in one click) to build these blueprints in game.",
		["blueprints.import"] = "Import a .blueprint file (Homestead or PlanBuild) or a .vbuild file: it is kept as a Homestead blueprint, ready to build in game.",
		["dialog.text"] = "Type the answer, then press OK (Enter).",
		["dialog.cancel"] = "Close without doing anything (Esc).",
		["build.search"] = "Find a piece by its name in every tab (wall, roof, stone floor…).",
		["build.snap"] = "On: as the game's hammer, the piece moves so its nearest snap point meets one of a piece already there (within half a metre). Off: it stays where it touches what you point at (the game's Alt).",
		["build.grid"] = "Where you point at the ground is rounded to this grid (from the middle of the plot) before the piece is put there; pieces pointed at are not. Off: as in the game.",
		["workshop.cut"] = "See the building from a height: nothing above it is shown (metres above the plot), and you can point at what is inside, to build there. Left: off.",
		["paste.clearSite"] = "Where a pasted building (its pieces) stands: the ground in its way, a mountain, a mound, is dug down to its lowest piece, a metre around it too; never raised. Trees, rocks, bushes and pickables there are taken away. One undo step with the paste.",
		["tools.blueprints"] = "Your blueprints (Homestead's, the Workshop's): paste one into this area.",
		["build.lift"] = "Back to no lift: the piece goes where the cursor points (on a piece, or the ground).",
		["build.turn"] = "How far , and . (or Alt + wheel) turn the piece. Shift turns by 1°.",
		["dialog.blueprintName"] = "The blueprint's name: Homestead lists it under this name in its hammer tab. Its file is named after it.",
		["dialog.blueprintDescription"] = "A few words about it, shown in the library (and to people you share the file with).",
		["dialog.blueprintTags"] = "Words to find it by, separated by commas: house, viking, stone, gate… The library's search looks through them.",
	};

	public static string Of(string key) => Texts.TryGetValue(key, out string? t) ? t : throw new KeyNotFoundException("No tip " + key);

	// The control explains itself on hover.
	public static T Tip<T>(this T c, string key) where T : Control
	{
		ToolTip.SetTip(c, Of(key));
		return c;
	}

	// A row's label tells the same as its control.
	public static void Label(Control label, Control input)
	{
		if (ToolTip.GetTip(input) is { } t)
		{
			ToolTip.SetTip(label, t);
		}
	}

	// The object kinds, as the View panel and the Area chips switch them.
	public static string Kind(ObjectKind k) => k switch
	{
		ObjectKind.Buildings => "Pieces built by players.",
		ObjectKind.Ruins => "Ruins, dungeon entrances and other generated structures (spoiler).",
		ObjectKind.Trees => "Trees, logs and stumps.",
		ObjectKind.Rocks => "Rocks and boulders.",
		ObjectKind.Ore => "Copper, tin, silver and other deposits (spoiler).",
		ObjectKind.Bushes => "Bushes, shrubs and ferns.",
		ObjectKind.Pickables => "Mushrooms, berries, flowers, stones and other things to pick up.",
		ObjectKind.Animals => "Boars, wolves, lox, hens, deer and other creatures players tamed (wild ones are under Other objects).",
		ObjectKind.Runestones => "The world's runestones. They can be picked and deleted (the game builds them from their location, so they cannot be moved or copied).",
		_ => "Everything else the save holds.",
	};

	public static string Overlay(Overlays.Layer l) => l switch
	{
		Overlays.Layer.Borders => Of("overlay.borders"),
		Overlays.Layer.Markers => Of("overlay.markers"),
		Overlays.Layer.Wards => Of("overlay.wards"),
		Overlays.Layer.Stations => Of("overlay.stations"),
		_ => Of("overlay.flatten"),
	};
}
